#!/usr/bin/env bash
# script to modify localhost to 127.0.0.2
# add facebook to resolve to 8.8.8.8

sudo sed -i -e 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo echo "8.8.8.8 facebook" | tee -a /etc/hosts
